"""
history.py

Provides temporary in-memory storage of acquisition records.

Responsibilities
----------------
- Store recent acquisition records.
- Remove records older than the configured retention period.
- Provide access to the current history.

History is intended for real-time visualization only.
It does not permanently save data.
"""

from collections import deque
from datetime import datetime, timedelta

from config import load_config


class History:
    """
    Stores recent acquisition records in RAM.
    """

    def __init__(self):
        """
        Create a History object.

        The retention time is loaded from config.json.
        """

        config = load_config()

        retention_hours = config["history"]["retention_hours"]

        self.retention = timedelta(hours=retention_hours)

        # Stores acquisition records in chronological order.
        self.records = deque()

    def add(self, record):
        """
        Add one acquisition record to history.

        Parameters
        ----------
        record : dict
            Acquisition record generated by main.py.
        """

        self.records.append(record)

        self._remove_old_records()

    def get_records(self):
        """
        Return all acquisition records currently stored.

        Returns
        -------
        list
            Acquisition records in chronological order.
        """

        return list(self.records)

    def clear(self):
        """
        Remove all acquisition records from history.
        """

        self.records.clear()

    def _remove_old_records(self):
        """
        Remove acquisition records older than the configured
        retention time.
        """

        now = datetime.now()

        while self.records:

            oldest_record = self.records[0]

            timestamp = oldest_record["Timestamp"]

            if now - timestamp <= self.retention:
                break

            self.records.popleft()